//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFExtensions.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLDates
    {
        public string Username { get; set; }
        public System.DateTime Rundate { get; set; }
        public string AppName { get; set; }
    }
}
